{*******************************************************}
{                                                       }
{ Import  unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

{} unit FILEHISTORYAPI_D2006;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  CommCtrl,
  SysUtils,
  Classes,
  Menus,
  ActiveX,
  ToolsAPI,
  FileHistoryAPI;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..4] of string = (
'hsBuffer'
,'hsFile'
,'hsLocalFile'
,'hsRemoteRevision'
,'hsActiveRevision'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,hsBuffer));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,hsFile));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,hsLocalFile));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,hsRemoteRevision));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,hsActiveRevision));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

procedure _mreg_0;
begin
end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
