{*******************************************************}
{                                                       }
{ Import  unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

{} unit IDREMOTECMDSERVER_D2006;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses rtti, 
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Classes,
  IdAssignedNumbers,
  IdTCPClient,
  IdTCPServer,
  IdRemoteCMDServer;
implementation
  var vmtMethodList:TStringList; 
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TIdPeerThread;
p1 : TIdTCPClient;
p2 : String;
p3 : String;
p4 : String) of object;

_T1 = procedure (p0 : TIdPeerThread;
p1 : TIdTCPClient;
p2 : String) of object;

_T2 = _T1;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TIdRemoteCMDServer
);
 function __getFullMethodName(sclassName, smethodName:String):String; 
 begin 
   result := format('%s.%s',[sClassName, sMethodName]) 
 end; 
procedure fillVMTProcs();
var
  ctx : TRttiContext;
  t:TRttiType;
  m:TRttiMethod;
  i:Integer;
begin
  ctx := TRttiContext.Create;
  try
    for i := 0 to length(classList) - 1 do
    begin
      t:=ctx.GetType(classList[i].ClassInfo);
      for m in t.GetMethods  do
      begin
        if m.DispatchKind = dkVtable then
        vmtMethodList.addObject(__getFullMethodName(classList[i].className,m.Name), pointer(m.VirtualIndex*4));
      end;
      t.free;
    end;
  finally
    ctx.free;
  end;
end;
function getVMTProcAddr(className, MethodName:String;oldAddr:Integer):Pointer;
var i:Integer;
begin
  i:=vmtMethodList.indexOf(__getFullMethodName(className,methodName));
  if i>-1 then 
    result:=pointer(vmtMethodList.Objects[i])
  else 
  result:=pointer(oldAddr);
end;  
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
//RegRegisterMethod(TIdRemoteCMDServer,'DoCMD',TypeInfo(_T0),[TypeInfo(TIdPeerThread),TypeInfo(TIdTCPClient),TypeInfo(String),TypeInfo(String),TypeInfo(String)], pointer(100));
RegRegisterMethod(TIdRemoteCMDServer,'DoCMD',TypeInfo(_T0),[TypeInfo(TIdPeerThread),TypeInfo(TIdTCPClient),TypeInfo(String),TypeInfo(String),TypeInfo(String)],  getVMTProcAddr('TIdRemoteCMDServer','DoCMD',100));


RegRegisterMethod(TIdRemoteCMDServer,'SendError',TypeInfo(_T1),[
TypeInfo(TIdPeerThread),
TypeInfo(TIdTCPClient),
TypeInfo(String)],Addr(TIdRemoteCMDServer.SendError));

RegRegisterMethod(TIdRemoteCMDServer,'SendResults',TypeInfo(_T2),[
TypeInfo(TIdPeerThread),
TypeInfo(TIdTCPClient),
TypeInfo(String)],Addr(TIdRemoteCMDServer.SendResults));

end;
initialization
 vmtMethodList:=TStringList.Create;
vmtMethodList.sorted:=true;
vmtMethodList.duplicates:=dupIgnore;
fillVMTProcs;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
vmtMethodList.free

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
