{*******************************************************}
{                                                       }
{ Import  unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

{} unit IDTELNETSERVER_D2006;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses rtti, 
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Classes,
  IdAssignedNumbers,
  IdTCPServer,
  IdThreadMgr,
  IdThreadMgrDefault,
  IdTelnetServer;
implementation
  var vmtMethodList:TStringList; 
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (p0 : TIdPeerThread;
const p1 : string;
const p2 : string): Boolean of object;

_T1 = procedure (p0 : TIdPeerThread) of object;

function __DC__GetTIdTelnetPeerThread__TelnetData(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIdTelnetPeerThread(Instance).TelnetData);
end;

procedure __RegisterProps;
begin
RegisterProperty(TIdTelnetPeerThread,'TelnetData',__DC__GetTIdTelnetPeerThread__TelnetData,nil);
end;

const __ConstNames0 : array[0..0] of string = (
'GLoginAttempts'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,GLoginAttempts));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..2] of TClass = (
TIdTelnetPeerThread,
TIdTelnetServer,
TTelnetData
);
 function __getFullMethodName(sclassName, smethodName:String):String; 
 begin 
   result := format('%s.%s',[sClassName, sMethodName]) 
 end; 
procedure fillVMTProcs();
var
  ctx : TRttiContext;
  t:TRttiType;
  m:TRttiMethod;
  i:Integer;
begin
  ctx := TRttiContext.Create;
  try
    for i := 0 to length(classList) - 1 do
    begin
      t:=ctx.GetType(classList[i].ClassInfo);
      for m in t.GetMethods  do
      begin
        if m.DispatchKind = dkVtable then
        vmtMethodList.addObject(__getFullMethodName(classList[i].className,m.Name), pointer(m.VirtualIndex*4));
      end;
      t.free;
    end;
  finally
    ctx.free;
  end;
end;
function getVMTProcAddr(className, MethodName:String;oldAddr:Integer):Pointer;
var i:Integer;
begin
  i:=vmtMethodList.indexOf(__getFullMethodName(className,methodName));
  if i>-1 then 
    result:=pointer(vmtMethodList.Objects[i])
  else 
  result:=pointer(oldAddr);
end;  
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
//RegRegisterMethod(TIdTelnetServer,'DoAuthenticate',TypeInfo(_T0),[TypeInfo(TIdPeerThread),TypeInfo(string),TypeInfo(string),TypeInfo(Boolean)], pointer(100));
RegRegisterMethod(TIdTelnetServer,'DoAuthenticate',TypeInfo(_T0),[TypeInfo(TIdPeerThread),TypeInfo(string),TypeInfo(string),TypeInfo(Boolean)],  getVMTProcAddr('TIdTelnetServer','DoAuthenticate',100));


//RegRegisterMethod(TIdTelnetServer,'DoNegotiate',TypeInfo(_T1),[TypeInfo(TIdPeerThread)], pointer(104));
RegRegisterMethod(TIdTelnetServer,'DoNegotiate',TypeInfo(_T1),[TypeInfo(TIdPeerThread)],  getVMTProcAddr('TIdTelnetServer','DoNegotiate',104));


end;
initialization
 vmtMethodList:=TStringList.Create;
vmtMethodList.sorted:=true;
vmtMethodList.duplicates:=dupIgnore;
fillVMTProcs;
_mreg_0;
RegisterEvent(TypeInfo(TAuthenticationEvent),[
TypeInfo(TIdPeerThread),
TypeInfo(string),
TypeInfo(string),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TIdTelnetNegotiateEvent),[
TypeInfo(TIdPeerThread)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
vmtMethodList.free

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
