{*******************************************************}
{                                                       }
{ Import  unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

{} unit REGSTR_D2006;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  classes,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  RegStr;
function Convert_DSKTLSYSTEMTIMEToVariant(var R : _DSKTLSYSTEMTIME) : OleVariant;
function ConvertVariantTo_DSKTLSYSTEMTIME(const V : OleVariant) : _DSKTLSYSTEMTIME;
function ConvertDSKTLSYSTEMTIMEToVariant(var R : DSKTLSYSTEMTIME) : OleVariant;
function ConvertVariantToDSKTLSYSTEMTIME(const V : OleVariant) : DSKTLSYSTEMTIME;
function ConvertTDSKTLSystemTimeToVariant(var R : TDSKTLSystemTime) : OleVariant;
function ConvertVariantToTDSKTLSystemTime(const V : OleVariant) : TDSKTLSystemTime;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type ___DSKTLSYSTEMTIME__Wrapper = class(TDCRecordWrapper)
private
fR : _DSKTLSYSTEMTIME;
public
function GetRecordPtr : pointer; override;
published
procedure setwYear(const val : Word);
function getwYear : Word;
property wYear : Word read getwYear write setwYear;
procedure setwMonth(const val : Word);
function getwMonth : Word;
property wMonth : Word read getwMonth write setwMonth;
procedure setwDayOfWeek(const val : Word);
function getwDayOfWeek : Word;
property wDayOfWeek : Word read getwDayOfWeek write setwDayOfWeek;
procedure setwDay(const val : Word);
function getwDay : Word;
property wDay : Word read getwDay write setwDay;
procedure setwHour(const val : Word);
function getwHour : Word;
property wHour : Word read getwHour write setwHour;
procedure setwMinute(const val : Word);
function getwMinute : Word;
property wMinute : Word read getwMinute write setwMinute;
procedure setwSecond(const val : Word);
function getwSecond : Word;
property wSecond : Word read getwSecond write setwSecond;
procedure setwMilliseconds(const val : Word);
function getwMilliseconds : Word;
property wMilliseconds : Word read getwMilliseconds write setwMilliseconds;
procedure setwResult(const val : Word);
function getwResult : Word;
property wResult : Word read getwResult write setwResult;
end;
type __DSKTLSYSTEMTIME__Wrapper = class(TDCRecordWrapper)
private
fR : DSKTLSYSTEMTIME;
public
function GetRecordPtr : pointer; override;
published
procedure setwYear(const val : Word);
function getwYear : Word;
property wYear : Word read getwYear write setwYear;
procedure setwMonth(const val : Word);
function getwMonth : Word;
property wMonth : Word read getwMonth write setwMonth;
procedure setwDayOfWeek(const val : Word);
function getwDayOfWeek : Word;
property wDayOfWeek : Word read getwDayOfWeek write setwDayOfWeek;
procedure setwDay(const val : Word);
function getwDay : Word;
property wDay : Word read getwDay write setwDay;
procedure setwHour(const val : Word);
function getwHour : Word;
property wHour : Word read getwHour write setwHour;
procedure setwMinute(const val : Word);
function getwMinute : Word;
property wMinute : Word read getwMinute write setwMinute;
procedure setwSecond(const val : Word);
function getwSecond : Word;
property wSecond : Word read getwSecond write setwSecond;
procedure setwMilliseconds(const val : Word);
function getwMilliseconds : Word;
property wMilliseconds : Word read getwMilliseconds write setwMilliseconds;
procedure setwResult(const val : Word);
function getwResult : Word;
property wResult : Word read getwResult write setwResult;
end;
type __TDSKTLSystemTime__Wrapper = class(TDCRecordWrapper)
private
fR : TDSKTLSystemTime;
public
function GetRecordPtr : pointer; override;
published
procedure setwYear(const val : Word);
function getwYear : Word;
property wYear : Word read getwYear write setwYear;
procedure setwMonth(const val : Word);
function getwMonth : Word;
property wMonth : Word read getwMonth write setwMonth;
procedure setwDayOfWeek(const val : Word);
function getwDayOfWeek : Word;
property wDayOfWeek : Word read getwDayOfWeek write setwDayOfWeek;
procedure setwDay(const val : Word);
function getwDay : Word;
property wDay : Word read getwDay write setwDay;
procedure setwHour(const val : Word);
function getwHour : Word;
property wHour : Word read getwHour write setwHour;
procedure setwMinute(const val : Word);
function getwMinute : Word;
property wMinute : Word read getwMinute write setwMinute;
procedure setwSecond(const val : Word);
function getwSecond : Word;
property wSecond : Word read getwSecond write setwSecond;
procedure setwMilliseconds(const val : Word);
function getwMilliseconds : Word;
property wMilliseconds : Word read getwMilliseconds write setwMilliseconds;
procedure setwResult(const val : Word);
function getwResult : Word;
property wResult : Word read getwResult write setwResult;
end;
function ___DSKTLSYSTEMTIME__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwYear(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wYear := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwYear : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wYear;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwMonth(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wMonth := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwMonth : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wMonth;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwDayOfWeek(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wDayOfWeek := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwDayOfWeek : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wDayOfWeek;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwDay(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wDay := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwDay : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wDay;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwHour(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wHour := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwHour : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wHour;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwMinute(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wMinute := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwMinute : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wMinute;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwSecond(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wSecond := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwSecond : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wSecond;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwMilliseconds(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wMilliseconds := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwMilliseconds : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wMilliseconds;
end;
procedure ___DSKTLSYSTEMTIME__Wrapper.setwResult(const val : Word);
begin
_DSKTLSYSTEMTIME(GetRecordPtr^).wResult := val;
end;
function ___DSKTLSYSTEMTIME__Wrapper.getwResult : Word;
begin
result := _DSKTLSYSTEMTIME(GetRecordPtr^).wResult;
end;
function __DSKTLSYSTEMTIME__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwYear(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wYear := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwYear : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wYear;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwMonth(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wMonth := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwMonth : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wMonth;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwDayOfWeek(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wDayOfWeek := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwDayOfWeek : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wDayOfWeek;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwDay(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wDay := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwDay : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wDay;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwHour(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wHour := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwHour : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wHour;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwMinute(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wMinute := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwMinute : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wMinute;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwSecond(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wSecond := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwSecond : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wSecond;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwMilliseconds(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wMilliseconds := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwMilliseconds : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wMilliseconds;
end;
procedure __DSKTLSYSTEMTIME__Wrapper.setwResult(const val : Word);
begin
DSKTLSYSTEMTIME(GetRecordPtr^).wResult := val;
end;
function __DSKTLSYSTEMTIME__Wrapper.getwResult : Word;
begin
result := DSKTLSYSTEMTIME(GetRecordPtr^).wResult;
end;
function __TDSKTLSystemTime__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TDSKTLSystemTime__Wrapper.setwYear(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wYear := val;
end;
function __TDSKTLSystemTime__Wrapper.getwYear : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wYear;
end;
procedure __TDSKTLSystemTime__Wrapper.setwMonth(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wMonth := val;
end;
function __TDSKTLSystemTime__Wrapper.getwMonth : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wMonth;
end;
procedure __TDSKTLSystemTime__Wrapper.setwDayOfWeek(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wDayOfWeek := val;
end;
function __TDSKTLSystemTime__Wrapper.getwDayOfWeek : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wDayOfWeek;
end;
procedure __TDSKTLSystemTime__Wrapper.setwDay(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wDay := val;
end;
function __TDSKTLSystemTime__Wrapper.getwDay : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wDay;
end;
procedure __TDSKTLSystemTime__Wrapper.setwHour(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wHour := val;
end;
function __TDSKTLSystemTime__Wrapper.getwHour : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wHour;
end;
procedure __TDSKTLSystemTime__Wrapper.setwMinute(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wMinute := val;
end;
function __TDSKTLSystemTime__Wrapper.getwMinute : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wMinute;
end;
procedure __TDSKTLSystemTime__Wrapper.setwSecond(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wSecond := val;
end;
function __TDSKTLSystemTime__Wrapper.getwSecond : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wSecond;
end;
procedure __TDSKTLSystemTime__Wrapper.setwMilliseconds(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wMilliseconds := val;
end;
function __TDSKTLSystemTime__Wrapper.getwMilliseconds : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wMilliseconds;
end;
procedure __TDSKTLSystemTime__Wrapper.setwResult(const val : Word);
begin
TDSKTLSystemTime(GetRecordPtr^).wResult := val;
end;
function __TDSKTLSystemTime__Wrapper.getwResult : Word;
begin
result := TDSKTLSystemTime(GetRecordPtr^).wResult;
end;
function __DSKTLSYSTEMTIME_ : IDispatch;
begin
  result := ___DSKTLSYSTEMTIME__Wrapper.Create;
end;
function _DSKTLSYSTEMTIME_ : IDispatch;
begin
  result := __DSKTLSYSTEMTIME__Wrapper.Create;
end;
function _TDSKTLSystemTime_ : IDispatch;
begin
  result := __TDSKTLSystemTime__Wrapper.Create;
end;

type ___DSKTLSYSTEMTIME__Wrapper__ = class(___DSKTLSYSTEMTIME__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function ___DSKTLSYSTEMTIME__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function Convert_DSKTLSYSTEMTIMEToVariant(var R : _DSKTLSYSTEMTIME) : OleVariant;
var
__rw : ___DSKTLSYSTEMTIME__Wrapper__;
begin
__rw := ___DSKTLSYSTEMTIME__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantTo_DSKTLSYSTEMTIME(const V : OleVariant) : _DSKTLSYSTEMTIME;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := _DSKTLSYSTEMTIME((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __DSKTLSYSTEMTIME__Wrapper__ = class(__DSKTLSYSTEMTIME__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __DSKTLSYSTEMTIME__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertDSKTLSYSTEMTIMEToVariant(var R : DSKTLSYSTEMTIME) : OleVariant;
var
__rw : __DSKTLSYSTEMTIME__Wrapper__;
begin
__rw := __DSKTLSYSTEMTIME__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToDSKTLSYSTEMTIME(const V : OleVariant) : DSKTLSYSTEMTIME;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := DSKTLSYSTEMTIME((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __TDSKTLSystemTime__Wrapper__ = class(__TDSKTLSystemTime__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TDSKTLSystemTime__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTDSKTLSystemTimeToVariant(var R : TDSKTLSystemTime) : OleVariant;
var
__rw : __TDSKTLSystemTime__Wrapper__;
begin
__rw := __TDSKTLSystemTime__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTDSKTLSystemTime(const V : OleVariant) : TDSKTLSystemTime;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TDSKTLSystemTime((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..473] of string = (
'REGSTR_KEY_CLASS'
,'REGSTR_KEY_CONFIG'
,'REGSTR_KEY_ENUM'
,'REGSTR_KEY_ROOTENUM'
,'REGSTR_KEY_BIOSENUM'
,'REGSTR_KEY_PCMCIAENUM'
,'REGSTR_KEY_PCIENUM'
,'REGSTR_KEY_EISAENUM'
,'REGSTR_KEY_ISAENUM_NEC_98'
,'REGSTR_KEY_EISAENUM_NEC_98'
,'REGSTR_KEY_LOGCONFIG'
,'REGSTR_KEY_SYSTEMBOARD'
,'REGSTR_KEY_APM'
,'REGSTR_KEY_DOSOPTCDROM'
,'REGSTR_KEY_DOSOPTMOUSE'
,'REGSTR_DEFAULT_INSTANCE'
,'REGSTR_PATH_MOTHERBOARD'
,'REGSTR_PATH_SETUP'
,'REGSTR_PATH_PIFCONVERT'
,'REGSTR_PATH_MSDOSOPTS'
,'REGSTR_PATH_MSDOSEMU'
,'REGSTR_PATH_NOSUGGMSDOS'
,'REGSTR_PATH_NEWDOSBOX'
,'REGSTR_PATH_RUNONCE'
,'REGSTR_PATH_RUN'
,'REGSTR_PATH_RUNSERVICESONCE'
,'REGSTR_PATH_RUNSERVICES'
,'REGSTR_PATH_EXPLORER'
,'REGSTR_PATH_DETECT'
,'REGSTR_PATH_APPPATHS'
,'REGSTR_PATH_UNINSTALL'
,'REGSTR_PATH_REALMODENET'
,'REGSTR_PATH_NETEQUIV'
,'REGSTR_PATH_CVNETWORK'
,'REGSTR_PATH_IDCONFIGDB'
,'REGSTR_PATH_CLASS'
,'REGSTR_PATH_DISPLAYSETTINGS'
,'REGSTR_PATH_FONTS'
,'REGSTR_PATH_ENUM'
,'REGSTR_PATH_ROOT'
,'REGSTR_PATH_SERVICES'
,'REGSTR_PATH_VXD'
,'REGSTR_PATH_IOS'
,'REGSTR_PATH_VMM'
,'REGSTR_PATH_VPOWERD'
,'REGSTR_PATH_VNETSUP'
,'REGSTR_PATH_NWREDIR'
,'REGSTR_PATH_NCPSERVER'
,'REGSTR_PATH_IOARB'
,'REGSTR_PATH_ADDRARB'
,'REGSTR_PATH_DMAARB'
,'REGSTR_PATH_IRQARB'
,'REGSTR_PATH_CODEPAGE'
,'REGSTR_PATH_FILESYSTEM'
,'REGSTR_PATH_FILESYSTEM_NOVOLTRACK'
,'REGSTR_PATH_CDFS'
,'REGSTR_PATH_WINBOOT'
,'REGSTR_PATH_INSTALLEDFILES'
,'REGSTR_PATH_VMM32FILES'
,'REGSTR_MAX_VALUE_LENGTH'
,'REGSTR_VAL_BITSPERPIXEL'
,'REGSTR_VAL_RESOLUTION'
,'REGSTR_VAL_DPILOGICALX'
,'REGSTR_VAL_DPILOGICALY'
,'REGSTR_VAL_DPIPHYSICALX'
,'REGSTR_VAL_DPIPHYSICALY'
,'REGSTR_VAL_REFRESHRATE'
,'REGSTR_VAL_DISPLAYFLAGS'
,'REGSTR_PATH_CONTROLPANEL'
,'REGSTR_PATH_CONTROLSFOLDER'
,'REGSTR_VAL_DOSCP'
,'REGSTR_VAL_WINCP'
,'REGSTR_PATH_DYNA_ENUM'
,'REGSTR_VAL_HARDWARE_KEY'
,'REGSTR_VAL_ALLOCATION'
,'REGSTR_VAL_PROBLEM'
,'REGSTR_VAL_STATUS'
,'REGSTR_VAL_DONTUSEMEM'
,'REGSTR_VAL_SYSTEMROOT'
,'REGSTR_VAL_BOOTCOUNT'
,'REGSTR_VAL_REALNETSTART'
,'REGSTR_VAL_MEDIA'
,'REGSTR_VAL_CONFIG'
,'REGSTR_VAL_DEVICEPATH'
,'REGSTR_VAL_SRCPATH'
,'REGSTR_VAL_OLDWINDIR'
,'REGSTR_VAL_SETUPFLAGS'
,'REGSTR_VAL_REGOWNER'
,'REGSTR_VAL_REGORGANIZATION'
,'REGSTR_VAL_LICENSINGINFO'
,'REGSTR_VAL_OLDMSDOSVER'
,'REGSTR_VAL_FIRSTINSTALLDATETIME'
,'REGSTR_VAL_WRAPPER'
,'IT_COMPACT'
,'IT_TYPICAL'
,'IT_PORTABLE'
,'IT_CUSTOM'
,'REGSTR_KEY_SETUP'
,'REGSTR_VAL_BOOTDIR'
,'REGSTR_VAL_WINBOOTDIR'
,'REGSTR_VAL_WINDIR'
,'REGSTR_VAL_APPINSTPATH'
,'REGSTR_PATH_EBD'
,'REGSTR_KEY_EBDFILESLOCAL'
,'REGSTR_KEY_EBDFILESKEYBOARD'
,'REGSTR_KEY_EBDAUTOEXECBATLOCAL'
,'REGSTR_KEY_EBDAUTOEXECBATKEYBOARD'
,'REGSTR_KEY_EBDCONFIGSYSLOCAL'
,'REGSTR_KEY_EBDCONFIGSYSKEYBOARD'
,'REGSTR_VAL_MSDOSMODE'
,'REGSTR_VAL_MSDOSMODEDISCARD'
,'REGSTR_VAL_DOSOPTGLOBALFLAGS'
,'DOSOPTGF_DEFCLEAN'
,'REGSTR_VAL_DOSOPTFLAGS'
,'REGSTR_VAL_OPTORDER'
,'REGSTR_VAL_CONFIGSYS'
,'REGSTR_VAL_AUTOEXEC'
,'REGSTR_VAL_STDDOSOPTION'
,'DOSOPTF_DEFAULT'
,'DOSOPTF_SUPPORTED'
,'DOSOPTF_ALWAYSUSE'
,'DOSOPTF_USESPMODE'
,'DOSOPTF_PROVIDESUMB'
,'DOSOPTF_NEEDSETUP'
,'DOSOPTF_INDOSSTART'
,'DOSOPTF_MULTIPLE'
,'SUF_FIRSTTIME'
,'SUF_EXPRESS'
,'SUF_BATCHINF'
,'SUF_CLEAN'
,'SUF_INSETUP'
,'SUF_NETSETUP'
,'SUF_NETHDBOOT'
,'SUF_NETRPLBOOT'
,'SUF_SBSCOPYOK'
,'REGSTR_VAL_DOSPAGER'
,'REGSTR_VAL_VXDGROUPS'
,'REGSTR_VAL_VPOWERDFLAGS'
,'VPDF_DISABLEPWRMGMT'
,'VPDF_FORCEAPM10MODE'
,'VPDF_SKIPINTELSLCHECK'
,'VPDF_DISABLEPWRSTATUSPOLL'
,'REGSTR_VAL_WORKGROUP'
,'REGSTR_VAL_DIRECTHOST'
,'REGSTR_VAL_FILESHARING'
,'REGSTR_VAL_PRINTSHARING'
,'REGSTR_VAL_FIRSTNETDRIVE'
,'REGSTR_VAL_MAXCONNECTIONS'
,'REGSTR_VAL_APISUPPORT'
,'REGSTR_VAL_MAXRETRY'
,'REGSTR_VAL_MINRETRY'
,'REGSTR_VAL_SUPPORTLFN'
,'REGSTR_VAL_SUPPORTBURST'
,'REGSTR_VAL_SUPPORTTUNNELLING'
,'REGSTR_VAL_FULLTRACE'
,'REGSTR_VAL_READCACHING'
,'REGSTR_VAL_SHOWDOTS'
,'REGSTR_VAL_GAPTIME'
,'REGSTR_VAL_SEARCHMODE'
,'REGSTR_VAL_SHELLVERSION'
,'REGSTR_VAL_MAXLIP'
,'REGSTR_VAL_PRESERVECASE'
,'REGSTR_VAL_OPTIMIZESFN'
,'REGSTR_VAL_NCP_BROWSEMASTER'
,'REGSTR_VAL_NCP_USEPEERBROWSING'
,'REGSTR_VAL_NCP_USESAP'
,'REGSTR_VAL_WIN31FILESYSTEM'
,'REGSTR_VAL_PRESERVELONGNAMES'
,'REGSTR_VAL_DRIVEWRITEBEHIND'
,'REGSTR_VAL_ASYNCFILECOMMIT'
,'REGSTR_VAL_PATHCACHECOUNT'
,'REGSTR_VAL_NAMECACHECOUNT'
,'REGSTR_VAL_CONTIGFILEALLOC'
,'REGSTR_VAL_VOLIDLETIMEOUT'
,'REGSTR_VAL_BUFFIDLETIMEOUT'
,'REGSTR_VAL_BUFFAGETIMEOUT'
,'REGSTR_VAL_NAMENUMERICTAIL'
,'REGSTR_VAL_READAHEADTHRESHOLD'
,'REGSTR_VAL_DOUBLEBUFFER'
,'REGSTR_VAL_SOFTCOMPATMODE'
,'REGSTR_VAL_DRIVESPINDOWN'
,'REGSTR_VAL_FORCEPMIO'
,'REGSTR_VAL_FORCERMIO'
,'REGSTR_VAL_LASTBOOTPMDRVS'
,'REGSTR_VAL_VIRTUALHDIRQ'
,'REGSTR_VAL_SRVNAMECACHECOUNT'
,'REGSTR_VAL_SRVNAMECACHE'
,'REGSTR_VAL_SRVNAMECACHENETPROV'
,'REGSTR_VAL_AUTOMOUNT'
,'REGSTR_VAL_COMPRESSIONMETHOD'
,'REGSTR_VAL_COMPRESSIONTHRESHOLD'
,'REGSTR_VAL_CDCACHESIZE'
,'REGSTR_VAL_CDPREFETCH'
,'REGSTR_VAL_CDPREFETCHTAIL'
,'REGSTR_VAL_CDRAWCACHE'
,'REGSTR_VAL_CDEXTERRORS'
,'REGSTR_VAL_CDSVDSENSE'
,'REGSTR_VAL_CDSHOWVERSIONS'
,'REGSTR_VAL_CDCOMPATNAMES'
,'REGSTR_VAL_CDNOREADAHEAD'
,'REGSTR_VAL_SCSI'
,'REGSTR_VAL_ESDI'
,'REGSTR_VAL_FLOP'
,'REGSTR_VAL_DISK'
,'REGSTR_VAL_CDROM'
,'REGSTR_VAL_SCANNER'
,'REGSTR_VAL_FLOPPY'
,'REGSTR_VAL_SCSITID'
,'REGSTR_VAL_SCSILUN'
,'REGSTR_VAL_REVLEVEL'
,'REGSTR_VAL_PRODUCTID'
,'REGSTR_VAL_PRODUCTTYPE'
,'REGSTR_VAL_DEVTYPE'
,'REGSTR_VAL_REMOVABLE'
,'REGSTR_VAL_CURDRVLET'
,'REGSTR_VAL_USRDRVLET'
,'REGSTR_VAL_SYNCDATAXFER'
,'REGSTR_VAL_AUTOINSNOTE'
,'REGSTR_VAL_DISCONNECT'
,'REGSTR_VAL_PMODE_INT13'
,'REGSTR_VAL_USERSETTINGS'
,'REGSTR_VAL_NOIDE'
,'REGSTR_VAL_DISKCLASSNAME'
,'REGSTR_VAL_CDROMCLASSNAME'
,'REGSTR_VAL_FORCELOAD'
,'REGSTR_VAL_FORCEFIFO'
,'REGSTR_VAL_FORCECL'
,'REGSTR_VAL_NOUSECLASS'
,'REGSTR_VAL_NOINSTALLCLASS'
,'REGSTR_VAL_NODISPLAYCLASS'
,'REGSTR_VAL_SILENTINSTALL'
,'REGSTR_KEY_PCMCIA_CLASS'
,'REGSTR_KEY_SCSI_CLASS'
,'REGSTR_KEY_PORTS_CLASS'
,'REGSTR_KEY_MEDIA_CLASS'
,'REGSTR_KEY_DISPLAY_CLASS'
,'REGSTR_KEY_KEYBOARD_CLASS'
,'REGSTR_KEY_MOUSE_CLASS'
,'REGSTR_KEY_MONITOR_CLASS'
,'REGSTR_VAL_PCMCIA_OPT'
,'PCMCIA_OPT_HAVE_SOCKET'
,'PCMCIA_OPT_AUTOMEM'
,'PCMCIA_OPT_NO_SOUND'
,'PCMCIA_OPT_NO_AUDIO'
,'PCMCIA_OPT_NO_APMREMOVE'
,'REGSTR_VAL_PCMCIA_MEM'
,'PCMCIA_DEF_MEMBEGIN'
,'PCMCIA_DEF_MEMEND'
,'PCMCIA_DEF_MEMLEN'
,'REGSTR_VAL_PCMCIA_ALLOC'
,'REGSTR_VAL_PCMCIA_ATAD'
,'REGSTR_VAL_PCMCIA_SIZ'
,'PCMCIA_DEF_MIN_REGION'
,'REGSTR_VAL_P1284MDL'
,'REGSTR_VAL_P1284MFG'
,'REGSTR_VAL_ISAPNP_RDP_OVERRIDE'
,'REGSTR_VAL_PCI'
,'REGSTR_PCI_OPTIONS'
,'REGSTR_PCI_DUAL_IDE'
,'PCI_OPTIONS_USE_BIOS'
,'PCI_OPTIONS_USE_IRQ_STEERING'
,'PCI_FLAG_NO_VIDEO_IRQ'
,'PCI_FLAG_PCMCIA_WANT_IRQ'
,'PCI_FLAG_DUAL_IDE'
,'PCI_FLAG_NO_ENUM_AT_ALL'
,'PCI_FLAG_ENUM_NO_RESOURCE'
,'PCI_FLAG_NEED_DWORD_ACCESS'
,'PCI_FLAG_SINGLE_FUNCTION'
,'PCI_FLAG_ALWAYS_ENABLED'
,'PCI_FLAG_IS_IDE'
,'PCI_FLAG_IS_VIDEO'
,'PCI_FLAG_FAIL_START'
,'REGSTR_KEY_CRASHES'
,'REGSTR_KEY_DANGERS'
,'REGSTR_KEY_DETMODVARS'
,'REGSTR_KEY_NDISINFO'
,'REGSTR_VAL_PROTINIPATH'
,'REGSTR_VAL_RESOURCES'
,'REGSTR_VAL_CRASHFUNCS'
,'REGSTR_VAL_CLASS'
,'REGSTR_VAL_DEVDESC'
,'REGSTR_VAL_BOOTCONFIG'
,'REGSTR_VAL_DETFUNC'
,'REGSTR_VAL_DETFLAGS'
,'REGSTR_VAL_COMPATIBLEIDS'
,'REGSTR_VAL_DETCONFIG'
,'REGSTR_VAL_VERIFYKEY'
,'REGSTR_VAL_COMINFO'
,'REGSTR_VAL_CARDSPECIFIC'
,'REGSTR_VAL_NETOSTYPE'
,'REGSTR_DATA_NETOS_NDIS'
,'REGSTR_DATA_NETOS_ODI'
,'REGSTR_VAL_MFG'
,'REGSTR_VAL_SCAN_ONLY_FIRST'
,'REGSTR_VAL_SHARE_IRQ'
,'REGSTR_VAL_NONSTANDARD_ATAPI'
,'REGSTR_VAL_IDE_FORCE_SERIALIZE'
,'REGSTR_VAL_MAX_HCID_LEN'
,'REGSTR_VAL_HWREV'
,'REGSTR_VAL_ENABLEINTS'
,'REGDF_NOTDETIO'
,'REGDF_NOTDETMEM'
,'REGDF_NOTDETIRQ'
,'REGDF_NOTDETDMA'
,'REGDF_NOTDETALL'
,'REGDF_NEEDFULLCONFIG'
,'REGDF_GENFORCEDCONFIG'
,'REGDF_NODETCONFIG'
,'REGDF_CONFLICTIO'
,'REGDF_CONFLICTMEM'
,'REGDF_CONFLICTIRQ'
,'REGDF_CONFLICTDMA'
,'REGDF_CONFLICTALL'
,'REGDF_MAPIRQ2TO9'
,'REGDF_NOTVERIFIED'
,'REGSTR_VAL_APMBIOSVER'
,'REGSTR_VAL_APMFLAGS'
,'REGSTR_VAL_SLSUPPORT'
,'REGSTR_VAL_MACHINETYPE'
,'REGSTR_VAL_SETUPMACHINETYPE'
,'REGSTR_MACHTYPE_UNKNOWN'
,'REGSTR_MACHTYPE_PHOENIX_PCAT'
,'REGSTR_MACHTYPE_HP_VECTRA'
,'REGSTR_MACHTYPE_ATT_PC'
,'REGSTR_MACHTYPE_ZENITH_PC'
,'REGSTR_VAL_APMMENUSUSPEND'
,'APMMENUSUSPEND_DISABLED'
,'APMMENUSUSPEND_ENABLED'
,'APMMENUSUSPEND_UNDOCKED'
,'APMMENUSUSPEND_NOCHANGE'
,'REGSTR_VAL_BUSTYPE'
,'REGSTR_VAL_CPU'
,'REGSTR_VAL_NDP'
,'REGSTR_VAL_PNPBIOSVER'
,'REGSTR_VAL_PNPSTRUCOFFSET'
,'REGSTR_VAL_PCIBIOSVER'
,'REGSTR_VAL_HWMECHANISM'
,'REGSTR_VAL_LASTPCIBUSNUM'
,'REGSTR_VAL_CONVMEM'
,'REGSTR_VAL_EXTMEM'
,'REGSTR_VAL_COMPUTERNAME'
,'REGSTR_VAL_BIOSNAME'
,'REGSTR_VAL_BIOSVERSION'
,'REGSTR_VAL_BIOSDATE'
,'REGSTR_VAL_MODEL'
,'REGSTR_VAL_SUBMODEL'
,'REGSTR_VAL_REVISION'
,'REGSTR_VAL_FIFODEPTH'
,'REGSTR_VAL_RDINTTHRESHOLD'
,'REGSTR_VAL_WRINTTHRESHOLD'
,'REGSTR_VAL_PRIORITY'
,'REGSTR_VAL_DRIVER'
,'REGSTR_VAL_FUNCDESC'
,'REGSTR_VAL_FORCEDCONFIG'
,'REGSTR_VAL_CONFIGFLAGS'
,'REGSTR_VAL_CSCONFIGFLAGS'
,'CONFIGFLAG_DISABLED'
,'CONFIGFLAG_REMOVED'
,'CONFIGFLAG_MANUAL_INSTALL'
,'CONFIGFLAG_IGNORE_BOOT_LC'
,'CONFIGFLAG_NET_BOOT'
,'CONFIGFLAG_REINSTALL'
,'CONFIGFLAG_FAILEDINSTALL'
,'CONFIGFLAG_CANTSTOPACHILD'
,'CONFIGFLAG_OKREMOVEROM'
,'CONFIGFLAG_NOREMOVEEXIT'
,'CSCONFIGFLAG_BITS'
,'CSCONFIGFLAG_DISABLED'
,'CSCONFIGFLAG_DO_NOT_CREATE'
,'CSCONFIGFLAG_DO_NOT_START'
,'DMSTATEFLAG_APPLYTOALL'
,'REGSTR_VAL_ROOT_DEVNODE'
,'REGSTR_VAL_RESERVED_DEVNODE'
,'REGSTR_PATH_MULTI_FUNCTION'
,'REGSTR_VAL_RESOURCE_MAP'
,'REGSTR_PATH_CHILD_PREFIX'
,'NUM_RESOURCE_MAP'
,'REGSTR_VAL_MF_FLAGS'
,'MF_FLAGS_EVEN_IF_NO_RESOURCE'
,'MF_FLAGS_NO_CREATE_IF_NO_RESOURCE'
,'MF_FLAGS_FILL_IN_UNKNOWN_RESOURCE'
,'MF_FLAGS_CREATE_BUT_NO_SHOW_DISABLED'
,'REGSTR_VAL_EISA_RANGES'
,'REGSTR_VAL_EISA_FUNCTIONS'
,'REGSTR_VAL_EISA_FUNCTIONS_MASK'
,'REGSTR_VAL_EISA_FLAGS'
,'REGSTR_VAL_EISA_SIMULATE_INT15'
,'REGSTR_VAL_EISA_RANGES_NEC_98'
,'REGSTR_VAL_EISA_FUNCTIONS_NEC_98'
,'REGSTR_VAL_EISA_FUNCTIONS_MASK_NEC_98'
,'REGSTR_VAL_EISA_FLAGS_NEC_98'
,'REGSTR_VAL_EISA_SIMULATE_INT15_NEC_98'
,'EISAFLAG_NO_IO_MERGE'
,'EISAFLAG_SLOT_IO_FIRST'
,'EISA_NO_MAX_FUNCTION'
,'NUM_EISA_RANGES'
,'REGSTR_VAL_DRVDESC'
,'REGSTR_VAL_DEVLOADER'
,'REGSTR_VAL_STATICVXD'
,'REGSTR_VAL_PROPERTIES'
,'REGSTR_VAL_MANUFACTURER'
,'REGSTR_VAL_EXISTS'
,'REGSTR_VAL_CMENUMFLAGS'
,'REGSTR_VAL_CMDRIVFLAGS'
,'REGSTR_VAL_ENUMERATOR'
,'REGSTR_VAL_DEVICEDRIVER'
,'REGSTR_VAL_PORTNAME'
,'REGSTR_VAL_POLLING'
,'REGSTR_VAL_DONTLOADIFCONFLICT'
,'REGSTR_VAL_PORTSUBCLASS'
,'REGSTR_VAL_NETCLEAN'
,'REGSTR_VAL_NOCMOSORFDPT'
,'REGSTR_VAL_COMVERIFYBASE'
,'REGSTR_KEY_OVERRIDE'
,'REGSTR_VAL_CONFIGMG'
,'REGSTR_VAL_SYSDM'
,'REGSTR_VAL_SYSDMFUNC'
,'REGSTR_VAL_PRIVATE'
,'REGSTR_VAL_PRIVATEFUNC'
,'REGSTR_VAL_DETECT'
,'REGSTR_VAL_DETECTFUNC'
,'REGSTR_VAL_ASKFORCONFIG'
,'REGSTR_VAL_ASKFORCONFIGFUNC'
,'REGSTR_VAL_WAITFORUNDOCK'
,'REGSTR_VAL_WAITFORUNDOCKFUNC'
,'REGSTR_VAL_REMOVEROMOKAY'
,'REGSTR_VAL_REMOVEROMOKAYFUNC'
,'REGSTR_VAL_CURCONFIG'
,'REGSTR_VAL_FRIENDLYNAME'
,'REGSTR_VAL_CURRENTCONFIG'
,'REGSTR_VAL_MAP'
,'REGSTR_VAL_ID'
,'REGSTR_VAL_DOCKED'
,'REGSTR_VAL_CHECKSUM'
,'REGSTR_VAL_HWDETECT'
,'REGSTR_VAL_PROFILEFLAGS'
,'REGSTR_KEY_PCMCIA'
,'REGSTR_KEY_PCUNKNOWN'
,'REGSTR_VAL_PCSSDRIVER'
,'REGSTR_KEY_PCMTD'
,'REGSTR_VAL_PCMTDRIVER'
,'REGSTR_VAL_HARDWAREID'
,'REGSTR_VAL_ENUMPROPPAGES'
,'REGSTR_VAL_BASICPROPERTIES'
,'REGSTR_VAL_PRIVATEPROBLEM'
,'REGSTR_KEY_CURRENT'
,'REGSTR_KEY_DEFAULT'
,'REGSTR_KEY_MODES'
,'REGSTR_VAL_MODE'
,'REGSTR_VAL_BPP'
,'REGSTR_VAL_HRES'
,'REGSTR_VAL_VRES'
,'REGSTR_VAL_FONTSIZE'
,'REGSTR_VAL_DRV'
,'REGSTR_VAL_GRB'
,'REGSTR_VAL_VDD'
,'REGSTR_VAL_VER'
,'REGSTR_VAL_MAXRES'
,'REGSTR_VAL_DPMS'
,'REGSTR_VAL_RESUMERESET'
,'REGSTR_VAL_DESCRIPTION'
,'REGSTR_KEY_SYSTEM'
,'REGSTR_KEY_USER'
,'REGSTR_VAL_DPI'
,'REGSTR_VAL_PCICOPTIONS'
,'PCIC_DEFAULT_IRQMASK'
,'PCIC_DEFAULT_IRQMASK_NEC_98'
,'PCIC_DEFAULT_NUMSOCKETS'
,'REGSTR_VAL_PCICIRQMAP'
,'REGSTR_PATH_APPEARANCE'
,'REGSTR_PATH_LOOKSCHEMES'
,'REGSTR_VAL_CUSTOMCOLORS'
,'REGSTR_PATH_SCREENSAVE'
,'REGSTR_VALUE_USESCRPASSWORD'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,REGSTR_KEY_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,REGSTR_KEY_CONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,REGSTR_KEY_ENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,REGSTR_KEY_ROOTENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,REGSTR_KEY_BIOSENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,REGSTR_KEY_PCMCIAENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,REGSTR_KEY_PCIENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,REGSTR_KEY_EISAENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,REGSTR_KEY_ISAENUM_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,REGSTR_KEY_EISAENUM_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,REGSTR_KEY_LOGCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,REGSTR_KEY_SYSTEMBOARD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,REGSTR_KEY_APM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,REGSTR_KEY_DOSOPTCDROM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,REGSTR_KEY_DOSOPTMOUSE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,REGSTR_DEFAULT_INSTANCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,REGSTR_PATH_MOTHERBOARD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,REGSTR_PATH_SETUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,REGSTR_PATH_PIFCONVERT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,REGSTR_PATH_MSDOSOPTS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,REGSTR_PATH_MSDOSEMU));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,REGSTR_PATH_NOSUGGMSDOS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,REGSTR_PATH_NEWDOSBOX));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,REGSTR_PATH_RUNONCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[24] ,REGSTR_PATH_RUN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[25] ,REGSTR_PATH_RUNSERVICESONCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[26] ,REGSTR_PATH_RUNSERVICES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[27] ,REGSTR_PATH_EXPLORER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[28] ,REGSTR_PATH_DETECT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[29] ,REGSTR_PATH_APPPATHS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[30] ,REGSTR_PATH_UNINSTALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[31] ,REGSTR_PATH_REALMODENET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[32] ,REGSTR_PATH_NETEQUIV));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[33] ,REGSTR_PATH_CVNETWORK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[34] ,REGSTR_PATH_IDCONFIGDB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[35] ,REGSTR_PATH_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[36] ,REGSTR_PATH_DISPLAYSETTINGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[37] ,REGSTR_PATH_FONTS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[38] ,REGSTR_PATH_ENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[39] ,REGSTR_PATH_ROOT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[40] ,REGSTR_PATH_SERVICES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[41] ,REGSTR_PATH_VXD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[42] ,REGSTR_PATH_IOS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[43] ,REGSTR_PATH_VMM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[44] ,REGSTR_PATH_VPOWERD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[45] ,REGSTR_PATH_VNETSUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[46] ,REGSTR_PATH_NWREDIR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[47] ,REGSTR_PATH_NCPSERVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[48] ,REGSTR_PATH_IOARB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[49] ,REGSTR_PATH_ADDRARB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[50] ,REGSTR_PATH_DMAARB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[51] ,REGSTR_PATH_IRQARB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[52] ,REGSTR_PATH_CODEPAGE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[53] ,REGSTR_PATH_FILESYSTEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[54] ,REGSTR_PATH_FILESYSTEM_NOVOLTRACK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[55] ,REGSTR_PATH_CDFS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[56] ,REGSTR_PATH_WINBOOT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[57] ,REGSTR_PATH_INSTALLEDFILES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[58] ,REGSTR_PATH_VMM32FILES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[59] ,REGSTR_MAX_VALUE_LENGTH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[60] ,REGSTR_VAL_BITSPERPIXEL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[61] ,REGSTR_VAL_RESOLUTION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[62] ,REGSTR_VAL_DPILOGICALX));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[63] ,REGSTR_VAL_DPILOGICALY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[64] ,REGSTR_VAL_DPIPHYSICALX));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[65] ,REGSTR_VAL_DPIPHYSICALY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[66] ,REGSTR_VAL_REFRESHRATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[67] ,REGSTR_VAL_DISPLAYFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[68] ,REGSTR_PATH_CONTROLPANEL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[69] ,REGSTR_PATH_CONTROLSFOLDER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[70] ,REGSTR_VAL_DOSCP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[71] ,REGSTR_VAL_WINCP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[72] ,REGSTR_PATH_DYNA_ENUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[73] ,REGSTR_VAL_HARDWARE_KEY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[74] ,REGSTR_VAL_ALLOCATION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[75] ,REGSTR_VAL_PROBLEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[76] ,REGSTR_VAL_STATUS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[77] ,REGSTR_VAL_DONTUSEMEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[78] ,REGSTR_VAL_SYSTEMROOT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[79] ,REGSTR_VAL_BOOTCOUNT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[80] ,REGSTR_VAL_REALNETSTART));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[81] ,REGSTR_VAL_MEDIA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[82] ,REGSTR_VAL_CONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[83] ,REGSTR_VAL_DEVICEPATH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[84] ,REGSTR_VAL_SRCPATH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[85] ,REGSTR_VAL_OLDWINDIR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[86] ,REGSTR_VAL_SETUPFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[87] ,REGSTR_VAL_REGOWNER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[88] ,REGSTR_VAL_REGORGANIZATION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[89] ,REGSTR_VAL_LICENSINGINFO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[90] ,REGSTR_VAL_OLDMSDOSVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[91] ,REGSTR_VAL_FIRSTINSTALLDATETIME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[92] ,REGSTR_VAL_WRAPPER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[93] ,IT_COMPACT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[94] ,IT_TYPICAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[95] ,IT_PORTABLE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[96] ,IT_CUSTOM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[97] ,REGSTR_KEY_SETUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[98] ,REGSTR_VAL_BOOTDIR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[99] ,REGSTR_VAL_WINBOOTDIR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[100] ,REGSTR_VAL_WINDIR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[101] ,REGSTR_VAL_APPINSTPATH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[102] ,REGSTR_PATH_EBD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[103] ,REGSTR_KEY_EBDFILESLOCAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[104] ,REGSTR_KEY_EBDFILESKEYBOARD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[105] ,REGSTR_KEY_EBDAUTOEXECBATLOCAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[106] ,REGSTR_KEY_EBDAUTOEXECBATKEYBOARD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[107] ,REGSTR_KEY_EBDCONFIGSYSLOCAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[108] ,REGSTR_KEY_EBDCONFIGSYSKEYBOARD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[109] ,REGSTR_VAL_MSDOSMODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[110] ,REGSTR_VAL_MSDOSMODEDISCARD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[111] ,REGSTR_VAL_DOSOPTGLOBALFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[112] ,DOSOPTGF_DEFCLEAN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[113] ,REGSTR_VAL_DOSOPTFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[114] ,REGSTR_VAL_OPTORDER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[115] ,REGSTR_VAL_CONFIGSYS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[116] ,REGSTR_VAL_AUTOEXEC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[117] ,REGSTR_VAL_STDDOSOPTION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[118] ,DOSOPTF_DEFAULT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[119] ,DOSOPTF_SUPPORTED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[120] ,DOSOPTF_ALWAYSUSE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[121] ,DOSOPTF_USESPMODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[122] ,DOSOPTF_PROVIDESUMB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[123] ,DOSOPTF_NEEDSETUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[124] ,DOSOPTF_INDOSSTART));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[125] ,DOSOPTF_MULTIPLE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[126] ,SUF_FIRSTTIME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[127] ,SUF_EXPRESS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[128] ,SUF_BATCHINF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[129] ,SUF_CLEAN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[130] ,SUF_INSETUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[131] ,SUF_NETSETUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[132] ,SUF_NETHDBOOT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[133] ,SUF_NETRPLBOOT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[134] ,SUF_SBSCOPYOK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[135] ,REGSTR_VAL_DOSPAGER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[136] ,REGSTR_VAL_VXDGROUPS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[137] ,REGSTR_VAL_VPOWERDFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[138] ,VPDF_DISABLEPWRMGMT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[139] ,VPDF_FORCEAPM10MODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[140] ,VPDF_SKIPINTELSLCHECK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[141] ,VPDF_DISABLEPWRSTATUSPOLL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[142] ,REGSTR_VAL_WORKGROUP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[143] ,REGSTR_VAL_DIRECTHOST));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[144] ,REGSTR_VAL_FILESHARING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[145] ,REGSTR_VAL_PRINTSHARING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[146] ,REGSTR_VAL_FIRSTNETDRIVE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[147] ,REGSTR_VAL_MAXCONNECTIONS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[148] ,REGSTR_VAL_APISUPPORT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[149] ,REGSTR_VAL_MAXRETRY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[150] ,REGSTR_VAL_MINRETRY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[151] ,REGSTR_VAL_SUPPORTLFN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[152] ,REGSTR_VAL_SUPPORTBURST));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[153] ,REGSTR_VAL_SUPPORTTUNNELLING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[154] ,REGSTR_VAL_FULLTRACE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[155] ,REGSTR_VAL_READCACHING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[156] ,REGSTR_VAL_SHOWDOTS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[157] ,REGSTR_VAL_GAPTIME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[158] ,REGSTR_VAL_SEARCHMODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[159] ,REGSTR_VAL_SHELLVERSION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[160] ,REGSTR_VAL_MAXLIP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[161] ,REGSTR_VAL_PRESERVECASE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[162] ,REGSTR_VAL_OPTIMIZESFN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[163] ,REGSTR_VAL_NCP_BROWSEMASTER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[164] ,REGSTR_VAL_NCP_USEPEERBROWSING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[165] ,REGSTR_VAL_NCP_USESAP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[166] ,REGSTR_VAL_WIN31FILESYSTEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[167] ,REGSTR_VAL_PRESERVELONGNAMES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[168] ,REGSTR_VAL_DRIVEWRITEBEHIND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[169] ,REGSTR_VAL_ASYNCFILECOMMIT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[170] ,REGSTR_VAL_PATHCACHECOUNT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[171] ,REGSTR_VAL_NAMECACHECOUNT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[172] ,REGSTR_VAL_CONTIGFILEALLOC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[173] ,REGSTR_VAL_VOLIDLETIMEOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[174] ,REGSTR_VAL_BUFFIDLETIMEOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[175] ,REGSTR_VAL_BUFFAGETIMEOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[176] ,REGSTR_VAL_NAMENUMERICTAIL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[177] ,REGSTR_VAL_READAHEADTHRESHOLD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[178] ,REGSTR_VAL_DOUBLEBUFFER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[179] ,REGSTR_VAL_SOFTCOMPATMODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[180] ,REGSTR_VAL_DRIVESPINDOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[181] ,REGSTR_VAL_FORCEPMIO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[182] ,REGSTR_VAL_FORCERMIO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[183] ,REGSTR_VAL_LASTBOOTPMDRVS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[184] ,REGSTR_VAL_VIRTUALHDIRQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[185] ,REGSTR_VAL_SRVNAMECACHECOUNT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[186] ,REGSTR_VAL_SRVNAMECACHE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[187] ,REGSTR_VAL_SRVNAMECACHENETPROV));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[188] ,REGSTR_VAL_AUTOMOUNT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[189] ,REGSTR_VAL_COMPRESSIONMETHOD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[190] ,REGSTR_VAL_COMPRESSIONTHRESHOLD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[191] ,REGSTR_VAL_CDCACHESIZE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[192] ,REGSTR_VAL_CDPREFETCH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[193] ,REGSTR_VAL_CDPREFETCHTAIL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[194] ,REGSTR_VAL_CDRAWCACHE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[195] ,REGSTR_VAL_CDEXTERRORS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[196] ,REGSTR_VAL_CDSVDSENSE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[197] ,REGSTR_VAL_CDSHOWVERSIONS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[198] ,REGSTR_VAL_CDCOMPATNAMES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[199] ,REGSTR_VAL_CDNOREADAHEAD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[200] ,REGSTR_VAL_SCSI));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[201] ,REGSTR_VAL_ESDI));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[202] ,REGSTR_VAL_FLOP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[203] ,REGSTR_VAL_DISK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[204] ,REGSTR_VAL_CDROM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[205] ,REGSTR_VAL_SCANNER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[206] ,REGSTR_VAL_FLOPPY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[207] ,REGSTR_VAL_SCSITID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[208] ,REGSTR_VAL_SCSILUN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[209] ,REGSTR_VAL_REVLEVEL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[210] ,REGSTR_VAL_PRODUCTID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[211] ,REGSTR_VAL_PRODUCTTYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[212] ,REGSTR_VAL_DEVTYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[213] ,REGSTR_VAL_REMOVABLE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[214] ,REGSTR_VAL_CURDRVLET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[215] ,REGSTR_VAL_USRDRVLET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[216] ,REGSTR_VAL_SYNCDATAXFER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[217] ,REGSTR_VAL_AUTOINSNOTE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[218] ,REGSTR_VAL_DISCONNECT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[219] ,REGSTR_VAL_PMODE_INT13));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[220] ,REGSTR_VAL_USERSETTINGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[221] ,REGSTR_VAL_NOIDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[222] ,REGSTR_VAL_DISKCLASSNAME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[223] ,REGSTR_VAL_CDROMCLASSNAME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[224] ,REGSTR_VAL_FORCELOAD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[225] ,REGSTR_VAL_FORCEFIFO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[226] ,REGSTR_VAL_FORCECL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[227] ,REGSTR_VAL_NOUSECLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[228] ,REGSTR_VAL_NOINSTALLCLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[229] ,REGSTR_VAL_NODISPLAYCLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[230] ,REGSTR_VAL_SILENTINSTALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[231] ,REGSTR_KEY_PCMCIA_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[232] ,REGSTR_KEY_SCSI_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[233] ,REGSTR_KEY_PORTS_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[234] ,REGSTR_KEY_MEDIA_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[235] ,REGSTR_KEY_DISPLAY_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[236] ,REGSTR_KEY_KEYBOARD_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[237] ,REGSTR_KEY_MOUSE_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[238] ,REGSTR_KEY_MONITOR_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[239] ,REGSTR_VAL_PCMCIA_OPT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[240] ,PCMCIA_OPT_HAVE_SOCKET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[241] ,PCMCIA_OPT_AUTOMEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[242] ,PCMCIA_OPT_NO_SOUND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[243] ,PCMCIA_OPT_NO_AUDIO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[244] ,PCMCIA_OPT_NO_APMREMOVE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[245] ,REGSTR_VAL_PCMCIA_MEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[246] ,PCMCIA_DEF_MEMBEGIN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[247] ,PCMCIA_DEF_MEMEND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[248] ,PCMCIA_DEF_MEMLEN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[249] ,REGSTR_VAL_PCMCIA_ALLOC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[250] ,REGSTR_VAL_PCMCIA_ATAD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[251] ,REGSTR_VAL_PCMCIA_SIZ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[252] ,PCMCIA_DEF_MIN_REGION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[253] ,REGSTR_VAL_P1284MDL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[254] ,REGSTR_VAL_P1284MFG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[255] ,REGSTR_VAL_ISAPNP_RDP_OVERRIDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[256] ,REGSTR_VAL_PCI));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[257] ,REGSTR_PCI_OPTIONS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[258] ,REGSTR_PCI_DUAL_IDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[259] ,PCI_OPTIONS_USE_BIOS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[260] ,PCI_OPTIONS_USE_IRQ_STEERING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[261] ,PCI_FLAG_NO_VIDEO_IRQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[262] ,PCI_FLAG_PCMCIA_WANT_IRQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[263] ,PCI_FLAG_DUAL_IDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[264] ,PCI_FLAG_NO_ENUM_AT_ALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[265] ,PCI_FLAG_ENUM_NO_RESOURCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[266] ,PCI_FLAG_NEED_DWORD_ACCESS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[267] ,PCI_FLAG_SINGLE_FUNCTION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[268] ,PCI_FLAG_ALWAYS_ENABLED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[269] ,PCI_FLAG_IS_IDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[270] ,PCI_FLAG_IS_VIDEO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[271] ,PCI_FLAG_FAIL_START));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[272] ,REGSTR_KEY_CRASHES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[273] ,REGSTR_KEY_DANGERS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[274] ,REGSTR_KEY_DETMODVARS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[275] ,REGSTR_KEY_NDISINFO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[276] ,REGSTR_VAL_PROTINIPATH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[277] ,REGSTR_VAL_RESOURCES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[278] ,REGSTR_VAL_CRASHFUNCS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[279] ,REGSTR_VAL_CLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[280] ,REGSTR_VAL_DEVDESC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[281] ,REGSTR_VAL_BOOTCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[282] ,REGSTR_VAL_DETFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[283] ,REGSTR_VAL_DETFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[284] ,REGSTR_VAL_COMPATIBLEIDS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[285] ,REGSTR_VAL_DETCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[286] ,REGSTR_VAL_VERIFYKEY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[287] ,REGSTR_VAL_COMINFO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[288] ,REGSTR_VAL_CARDSPECIFIC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[289] ,REGSTR_VAL_NETOSTYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[290] ,REGSTR_DATA_NETOS_NDIS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[291] ,REGSTR_DATA_NETOS_ODI));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[292] ,REGSTR_VAL_MFG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[293] ,REGSTR_VAL_SCAN_ONLY_FIRST));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[294] ,REGSTR_VAL_SHARE_IRQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[295] ,REGSTR_VAL_NONSTANDARD_ATAPI));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[296] ,REGSTR_VAL_IDE_FORCE_SERIALIZE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[297] ,REGSTR_VAL_MAX_HCID_LEN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[298] ,REGSTR_VAL_HWREV));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[299] ,REGSTR_VAL_ENABLEINTS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[300] ,REGDF_NOTDETIO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[301] ,REGDF_NOTDETMEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[302] ,REGDF_NOTDETIRQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[303] ,REGDF_NOTDETDMA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[304] ,REGDF_NOTDETALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[305] ,REGDF_NEEDFULLCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[306] ,REGDF_GENFORCEDCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[307] ,REGDF_NODETCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[308] ,REGDF_CONFLICTIO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[309] ,REGDF_CONFLICTMEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[310] ,REGDF_CONFLICTIRQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[311] ,REGDF_CONFLICTDMA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[312] ,REGDF_CONFLICTALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[313] ,REGDF_MAPIRQ2TO9));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[314] ,REGDF_NOTVERIFIED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[315] ,REGSTR_VAL_APMBIOSVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[316] ,REGSTR_VAL_APMFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[317] ,REGSTR_VAL_SLSUPPORT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[318] ,REGSTR_VAL_MACHINETYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[319] ,REGSTR_VAL_SETUPMACHINETYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[320] ,REGSTR_MACHTYPE_UNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[321] ,REGSTR_MACHTYPE_PHOENIX_PCAT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[322] ,REGSTR_MACHTYPE_HP_VECTRA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[323] ,REGSTR_MACHTYPE_ATT_PC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[324] ,REGSTR_MACHTYPE_ZENITH_PC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[325] ,REGSTR_VAL_APMMENUSUSPEND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[326] ,APMMENUSUSPEND_DISABLED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[327] ,APMMENUSUSPEND_ENABLED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[328] ,APMMENUSUSPEND_UNDOCKED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[329] ,APMMENUSUSPEND_NOCHANGE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[330] ,REGSTR_VAL_BUSTYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[331] ,REGSTR_VAL_CPU));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[332] ,REGSTR_VAL_NDP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[333] ,REGSTR_VAL_PNPBIOSVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[334] ,REGSTR_VAL_PNPSTRUCOFFSET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[335] ,REGSTR_VAL_PCIBIOSVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[336] ,REGSTR_VAL_HWMECHANISM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[337] ,REGSTR_VAL_LASTPCIBUSNUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[338] ,REGSTR_VAL_CONVMEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[339] ,REGSTR_VAL_EXTMEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[340] ,REGSTR_VAL_COMPUTERNAME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[341] ,REGSTR_VAL_BIOSNAME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[342] ,REGSTR_VAL_BIOSVERSION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[343] ,REGSTR_VAL_BIOSDATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[344] ,REGSTR_VAL_MODEL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[345] ,REGSTR_VAL_SUBMODEL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[346] ,REGSTR_VAL_REVISION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[347] ,REGSTR_VAL_FIFODEPTH));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[348] ,REGSTR_VAL_RDINTTHRESHOLD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[349] ,REGSTR_VAL_WRINTTHRESHOLD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[350] ,REGSTR_VAL_PRIORITY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[351] ,REGSTR_VAL_DRIVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[352] ,REGSTR_VAL_FUNCDESC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[353] ,REGSTR_VAL_FORCEDCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[354] ,REGSTR_VAL_CONFIGFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[355] ,REGSTR_VAL_CSCONFIGFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[356] ,CONFIGFLAG_DISABLED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[357] ,CONFIGFLAG_REMOVED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[358] ,CONFIGFLAG_MANUAL_INSTALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[359] ,CONFIGFLAG_IGNORE_BOOT_LC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[360] ,CONFIGFLAG_NET_BOOT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[361] ,CONFIGFLAG_REINSTALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[362] ,CONFIGFLAG_FAILEDINSTALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[363] ,CONFIGFLAG_CANTSTOPACHILD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[364] ,CONFIGFLAG_OKREMOVEROM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[365] ,CONFIGFLAG_NOREMOVEEXIT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[366] ,CSCONFIGFLAG_BITS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[367] ,CSCONFIGFLAG_DISABLED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[368] ,CSCONFIGFLAG_DO_NOT_CREATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[369] ,CSCONFIGFLAG_DO_NOT_START));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[370] ,DMSTATEFLAG_APPLYTOALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[371] ,REGSTR_VAL_ROOT_DEVNODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[372] ,REGSTR_VAL_RESERVED_DEVNODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[373] ,REGSTR_PATH_MULTI_FUNCTION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[374] ,REGSTR_VAL_RESOURCE_MAP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[375] ,REGSTR_PATH_CHILD_PREFIX));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[376] ,NUM_RESOURCE_MAP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[377] ,REGSTR_VAL_MF_FLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[378] ,MF_FLAGS_EVEN_IF_NO_RESOURCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[379] ,MF_FLAGS_NO_CREATE_IF_NO_RESOURCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[380] ,MF_FLAGS_FILL_IN_UNKNOWN_RESOURCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[381] ,MF_FLAGS_CREATE_BUT_NO_SHOW_DISABLED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[382] ,REGSTR_VAL_EISA_RANGES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[383] ,REGSTR_VAL_EISA_FUNCTIONS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[384] ,REGSTR_VAL_EISA_FUNCTIONS_MASK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[385] ,REGSTR_VAL_EISA_FLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[386] ,REGSTR_VAL_EISA_SIMULATE_INT15));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[387] ,REGSTR_VAL_EISA_RANGES_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[388] ,REGSTR_VAL_EISA_FUNCTIONS_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[389] ,REGSTR_VAL_EISA_FUNCTIONS_MASK_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[390] ,REGSTR_VAL_EISA_FLAGS_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[391] ,REGSTR_VAL_EISA_SIMULATE_INT15_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[392] ,EISAFLAG_NO_IO_MERGE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[393] ,EISAFLAG_SLOT_IO_FIRST));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[394] ,EISA_NO_MAX_FUNCTION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[395] ,NUM_EISA_RANGES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[396] ,REGSTR_VAL_DRVDESC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[397] ,REGSTR_VAL_DEVLOADER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[398] ,REGSTR_VAL_STATICVXD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[399] ,REGSTR_VAL_PROPERTIES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[400] ,REGSTR_VAL_MANUFACTURER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[401] ,REGSTR_VAL_EXISTS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[402] ,REGSTR_VAL_CMENUMFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[403] ,REGSTR_VAL_CMDRIVFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[404] ,REGSTR_VAL_ENUMERATOR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[405] ,REGSTR_VAL_DEVICEDRIVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[406] ,REGSTR_VAL_PORTNAME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[407] ,REGSTR_VAL_POLLING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[408] ,REGSTR_VAL_DONTLOADIFCONFLICT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[409] ,REGSTR_VAL_PORTSUBCLASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[410] ,REGSTR_VAL_NETCLEAN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[411] ,REGSTR_VAL_NOCMOSORFDPT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[412] ,REGSTR_VAL_COMVERIFYBASE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[413] ,REGSTR_KEY_OVERRIDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[414] ,REGSTR_VAL_CONFIGMG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[415] ,REGSTR_VAL_SYSDM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[416] ,REGSTR_VAL_SYSDMFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[417] ,REGSTR_VAL_PRIVATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[418] ,REGSTR_VAL_PRIVATEFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[419] ,REGSTR_VAL_DETECT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[420] ,REGSTR_VAL_DETECTFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[421] ,REGSTR_VAL_ASKFORCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[422] ,REGSTR_VAL_ASKFORCONFIGFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[423] ,REGSTR_VAL_WAITFORUNDOCK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[424] ,REGSTR_VAL_WAITFORUNDOCKFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[425] ,REGSTR_VAL_REMOVEROMOKAY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[426] ,REGSTR_VAL_REMOVEROMOKAYFUNC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[427] ,REGSTR_VAL_CURCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[428] ,REGSTR_VAL_FRIENDLYNAME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[429] ,REGSTR_VAL_CURRENTCONFIG));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[430] ,REGSTR_VAL_MAP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[431] ,REGSTR_VAL_ID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[432] ,REGSTR_VAL_DOCKED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[433] ,REGSTR_VAL_CHECKSUM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[434] ,REGSTR_VAL_HWDETECT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[435] ,REGSTR_VAL_PROFILEFLAGS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[436] ,REGSTR_KEY_PCMCIA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[437] ,REGSTR_KEY_PCUNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[438] ,REGSTR_VAL_PCSSDRIVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[439] ,REGSTR_KEY_PCMTD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[440] ,REGSTR_VAL_PCMTDRIVER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[441] ,REGSTR_VAL_HARDWAREID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[442] ,REGSTR_VAL_ENUMPROPPAGES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[443] ,REGSTR_VAL_BASICPROPERTIES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[444] ,REGSTR_VAL_PRIVATEPROBLEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[445] ,REGSTR_KEY_CURRENT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[446] ,REGSTR_KEY_DEFAULT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[447] ,REGSTR_KEY_MODES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[448] ,REGSTR_VAL_MODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[449] ,REGSTR_VAL_BPP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[450] ,REGSTR_VAL_HRES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[451] ,REGSTR_VAL_VRES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[452] ,REGSTR_VAL_FONTSIZE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[453] ,REGSTR_VAL_DRV));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[454] ,REGSTR_VAL_GRB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[455] ,REGSTR_VAL_VDD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[456] ,REGSTR_VAL_VER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[457] ,REGSTR_VAL_MAXRES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[458] ,REGSTR_VAL_DPMS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[459] ,REGSTR_VAL_RESUMERESET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[460] ,REGSTR_VAL_DESCRIPTION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[461] ,REGSTR_KEY_SYSTEM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[462] ,REGSTR_KEY_USER));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[463] ,REGSTR_VAL_DPI));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[464] ,REGSTR_VAL_PCICOPTIONS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[465] ,PCIC_DEFAULT_IRQMASK));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[466] ,PCIC_DEFAULT_IRQMASK_NEC_98));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[467] ,PCIC_DEFAULT_NUMSOCKETS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[468] ,REGSTR_VAL_PCICIRQMAP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[469] ,REGSTR_PATH_APPEARANCE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[470] ,REGSTR_PATH_LOOKSCHEMES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[471] ,REGSTR_VAL_CUSTOMCOLORS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[472] ,REGSTR_PATH_SCREENSAVE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[473] ,REGSTR_VALUE_USESCRPASSWORD));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const __ConstNames1 : array[0..222] of string = (
'REGSTR_VALUE_SCRPASSWORD'
,'REGSTR_VALUE_LOWPOWERTIMEOUT'
,'REGSTR_VALUE_POWEROFFTIMEOUT'
,'REGSTR_VALUE_LOWPOWERACTIVE'
,'REGSTR_VALUE_POWEROFFACTIVE'
,'REGSTR_PATH_WINDOWSAPPLETS'
,'REGSTR_PATH_SYSTRAY'
,'REGSTR_VAL_SYSTRAYSVCS'
,'REGSTR_VAL_SYSTRAYBATFLAGS'
,'REGSTR_VAL_SYSTRAYPCCARDFLAGS'
,'REGSTR_PATH_NETWORK_USERSETTINGS'
,'REGSTR_KEY_NETWORK_PERSISTENT'
,'REGSTR_KEY_NETWORK_RECENT'
,'REGSTR_VAL_REMOTE_PATH'
,'REGSTR_VAL_USER_NAME'
,'REGSTR_VAL_PROVIDER_NAME'
,'REGSTR_VAL_CONNECTION_TYPE'
,'REGSTR_VAL_UPGRADE'
,'REGSTR_KEY_LOGON'
,'REGSTR_VAL_MUSTBEVALIDATED'
,'REGSTR_VAL_RUNLOGINSCRIPT'
,'REGSTR_KEY_NETWORKPROVIDER'
,'REGSTR_PATH_NW32NETPROVIDER'
,'REGSTR_PATH_MS32NETPROVIDER'
,'REGSTR_VAL_AUTHENT_AGENT'
,'REGSTR_VAL_PREFREDIR'
,'REGSTR_VAL_AUTOSTART'
,'REGSTR_VAL_AUTOLOGON'
,'REGSTR_VAL_NETCARD'
,'REGSTR_VAL_DYNAMIC'
,'REGSTR_VAL_STATICDRIVE'
,'REGSTR_VAL_LOADHI'
,'REGSTR_VAL_LOADRMDRIVERS'
,'REGSTR_VAL_SETUPN'
,'REGSTR_VAL_SETUPNPATH'
,'REGSTR_VAL_WRKGRP_FORCEMAPPING'
,'REGSTR_VAL_WRKGRP_REQUIRED'
,'REGSTR_PATH_CURRENT_CONTROL_SET'
,'REGSTR_VAL_CURRENT_USER'
,'REGSTR_PATH_PWDPROVIDER'
,'REGSTR_VAL_PWDPROVIDER_PATH'
,'REGSTR_VAL_PWDPROVIDER_DESC'
,'REGSTR_VAL_PWDPROVIDER_CHANGEPWD'
,'REGSTR_VAL_PWDPROVIDER_CHANGEPWDHWND'
,'REGSTR_VAL_PWDPROVIDER_GETPWDSTATUS'
,'REGSTR_VAL_PWDPROVIDER_ISNP'
,'REGSTR_VAL_PWDPROVIDER_CHANGEORDER'
,'REGSTR_PATH_POLICIES'
,'REGSTR_PATH_UPDATE'
,'REGSTR_VALUE_ENABLE'
,'REGSTR_VALUE_VERBOSE'
,'REGSTR_VALUE_NETPATH'
,'REGSTR_VALUE_DEFAULTLOC'
,'REGSTR_KEY_NETWORK'
,'REGSTR_KEY_PRINTERS'
,'REGSTR_KEY_WINOLDAPP'
,'REGSTR_VAL_NOFILESHARING'
,'REGSTR_VAL_NOPRINTSHARING'
,'REGSTR_VAL_NOFILESHARINGCTRL'
,'REGSTR_VAL_NOPRINTSHARINGCTRL'
,'REGSTR_VAL_HIDESHAREPWDS'
,'REGSTR_VAL_DISABLEPWDCACHING'
,'REGSTR_VAL_ALPHANUMPWDS'
,'REGSTR_VAL_NETSETUP_DISABLE'
,'REGSTR_VAL_NETSETUP_NOCONFIGPAGE'
,'REGSTR_VAL_NETSETUP_NOIDPAGE'
,'REGSTR_VAL_NETSETUP_NOSECURITYPAGE'
,'REGSTR_VAL_SYSTEMCPL_NOVIRTMEMPAGE'
,'REGSTR_VAL_SYSTEMCPL_NODEVMGRPAGE'
,'REGSTR_VAL_SYSTEMCPL_NOCONFIGPAGE'
,'REGSTR_VAL_SYSTEMCPL_NOFILESYSPAGE'
,'REGSTR_VAL_DISPCPL_NODISPCPL'
,'REGSTR_VAL_DISPCPL_NOBACKGROUNDPAGE'
,'REGSTR_VAL_DISPCPL_NOSCRSAVPAGE'
,'REGSTR_VAL_DISPCPL_NOAPPEARANCEPAGE'
,'REGSTR_VAL_DISPCPL_NOSETTINGSPAGE'
,'REGSTR_VAL_SECCPL_NOSECCPL'
,'REGSTR_VAL_SECCPL_NOPWDPAGE'
,'REGSTR_VAL_SECCPL_NOADMINPAGE'
,'REGSTR_VAL_SECCPL_NOPROFILEPAGE'
,'REGSTR_VAL_PRINTERS_HIDETABS'
,'REGSTR_VAL_PRINTERS_NODELETE'
,'REGSTR_VAL_PRINTERS_NOADD'
,'REGSTR_VAL_WINOLDAPP_DISABLED'
,'REGSTR_VAL_WINOLDAPP_NOREALMODE'
,'REGSTR_VAL_NOENTIRENETWORK'
,'REGSTR_VAL_NOWORKGROUPCONTENTS'
,'REGSTR_VAL_MINPWDLEN'
,'REGSTR_VAL_PWDEXPIRATION'
,'REGSTR_VAL_WIN31PROVIDER'
,'REGSTR_VAL_DISABLEREGTOOLS'
,'REGSTR_PATH_WINLOGON'
,'REGSTR_VAL_LEGALNOTICECAPTION'
,'REGSTR_VAL_LEGALNOTICETEXT'
,'REGSTR_VAL_RESTRICTRUN'
,'REGSTR_KEY_POL_USERS'
,'REGSTR_KEY_POL_COMPUTERS'
,'REGSTR_KEY_POL_USERGROUPS'
,'REGSTR_KEY_POL_DEFAULT'
,'REGSTR_KEY_POL_USERGROUPDATA'
,'REGSTR_PATH_TIMEZONE'
,'REGSTR_VAL_TZBIAS'
,'REGSTR_VAL_TZDLTBIAS'
,'REGSTR_VAL_TZSTDBIAS'
,'REGSTR_VAL_TZACTBIAS'
,'REGSTR_VAL_TZDLTFLAG'
,'REGSTR_VAL_TZSTDSTART'
,'REGSTR_VAL_TZDLTSTART'
,'REGSTR_VAL_TZDLTNAME'
,'REGSTR_VAL_TZSTDNAME'
,'REGSTR_VAL_TZNOCHANGESTART'
,'REGSTR_VAL_TZNOCHANGEEND'
,'REGSTR_VAL_TZNOAUTOTIME'
,'REGSTR_PATH_FLOATINGPOINTPROCESSOR'
,'REGSTR_PATH_FLOATINGPOINTPROCESSOR0'
,'REGSTR_PATH_COMPUTRNAME'
,'REGSTR_VAL_COMPUTRNAME'
,'REGSTR_PATH_SHUTDOWN'
,'REGSTR_VAL_FORCEREBOOT'
,'REGSTR_VAL_SETUPPROGRAMRAN'
,'REGSTR_VAL_DOES_POLLING'
,'REGSTR_PATH_KNOWNDLLS'
,'REGSTR_PATH_KNOWN16DLLS'
,'REGSTR_PATH_CHECKVERDLLS'
,'REGSTR_PATH_WARNVERDLLS'
,'REGSTR_PATH_HACKINIFILE'
,'REGSTR_PATH_CHECKBADAPPS'
,'REGSTR_PATH_APPPATCH'
,'REGSTR_PATH_KNOWNVXDS'
,'REGSTR_VAL_UNINSTALLER_DISPLAYNAME'
,'REGSTR_VAL_UNINSTALLER_COMMANDLINE'
,'REGSTR_PATH_DESKTOP'
,'REGSTR_PATH_MOUSE'
,'REGSTR_PATH_KEYBOARD'
,'REGSTR_PATH_COLORS'
,'REGSTR_PATH_SOUND'
,'REGSTR_PATH_METRICS'
,'REGSTR_PATH_ICONS'
,'REGSTR_PATH_CURSORS'
,'REGSTR_PATH_CHECKDISK'
,'REGSTR_PATH_CHECKDISKSET'
,'REGSTR_PATH_CHECKDISKUDRVS'
,'REGSTR_PATH_FAULT'
,'REGSTR_VAL_FAULT_LOGFILE'
,'REGSTR_PATH_AEDEBUG'
,'REGSTR_VAL_AEDEBUG_DEBUGGER'
,'REGSTR_VAL_AEDEBUG_AUTO'
,'REGSTR_PATH_GRPCONV'
,'REGSTR_VAL_REGITEMDELETEMESSAGE'
,'REGSTR_PATH_LASTCHECK'
,'REGSTR_PATH_LASTOPTIMIZE'
,'REGSTR_PATH_LASTBACKUP'
,'REGSTR_PATH_CHKLASTCHECK'
,'REGSTR_PATH_CHKLASTSURFAN'
,'DTRESULTOK'
,'DTRESULTFIX'
,'DTRESULTPROB'
,'DTRESULTPART'
,'REGSTR_KEY_SHARES'
,'REGSTR_VAL_SHARES_FLAGS'
,'REGSTR_VAL_SHARES_PATH'
,'REGSTR_VAL_SHARES_REMARK'
,'REGSTR_VAL_SHARES_RW_PASS'
,'REGSTR_VAL_SHARES_RO_PASS'
,'REGSTR_PATH_PRINT'
,'REGSTR_PATH_PRINTERS'
,'REGSTR_PATH_PROVIDERS'
,'REGSTR_PATH_MONITORS'
,'REGSTR_PATH_ENVIRONMENTS'
,'REGSTR_VAL_START_ON_BOOT'
,'REGSTR_VAL_PRINTERS_MASK'
,'REGSTR_VAL_DOS_SPOOL_MASK'
,'REGSTR_KEY_CURRENT_ENV'
,'REGSTR_KEY_DRIVERS'
,'REGSTR_KEY_PRINT_PROC'
,'REGSTR_PATH_EVENTLABELS'
,'REGSTR_PATH_SCHEMES'
,'REGSTR_PATH_APPS'
,'REGSTR_PATH_APPS_DEFAULT'
,'REGSTR_PATH_NAMES'
,'REGSTR_PATH_MULTIMEDIA'
,'REGSTR_PATH_MULTIMEDIA_AUDIO'
,'REGSTR_PATH_MEDIARESOURCES'
,'REGSTR_PATH_MEDIAPROPERTIES'
,'REGSTR_PATH_PRIVATEPROPERTIES'
,'REGSTR_PATH_PUBLICPROPERTIES'
,'REGSTR_PATH_JOYOEM'
,'REGSTR_PATH_JOYCONFIG'
,'REGSTR_KEY_JOYCURR'
,'REGSTR_KEY_JOYSETTINGS'
,'REGSTR_VAL_JOYUSERVALUES'
,'REGSTR_VAL_JOYCALLOUT'
,'REGSTR_VAL_JOYNCONFIG'
,'REGSTR_VAL_JOYNOEMNAME'
,'REGSTR_VAL_JOYNOEMCALLOUT'
,'REGSTR_VAL_JOYOEMCALLOUT'
,'REGSTR_VAL_JOYOEMNAME'
,'REGSTR_VAL_JOYOEMDATA'
,'REGSTR_VAL_JOYOEMXYLABEL'
,'REGSTR_VAL_JOYOEMZLABEL'
,'REGSTR_VAL_JOYOEMRLABEL'
,'REGSTR_VAL_JOYOEMPOVLABEL'
,'REGSTR_VAL_JOYOEMULABEL'
,'REGSTR_VAL_JOYOEMVLABEL'
,'REGSTR_VAL_JOYOEMTESTMOVEDESC'
,'REGSTR_VAL_JOYOEMTESTBUTTONDESC'
,'REGSTR_VAL_JOYOEMTESTMOVECAP'
,'REGSTR_VAL_JOYOEMTESTBUTTONCAP'
,'REGSTR_VAL_JOYOEMTESTWINCAP'
,'REGSTR_VAL_JOYOEMCALCAP'
,'REGSTR_VAL_JOYOEMCALWINCAP'
,'REGSTR_VAL_JOYOEMCAL1'
,'REGSTR_VAL_JOYOEMCAL2'
,'REGSTR_VAL_JOYOEMCAL3'
,'REGSTR_VAL_JOYOEMCAL4'
,'REGSTR_VAL_JOYOEMCAL5'
,'REGSTR_VAL_JOYOEMCAL6'
,'REGSTR_VAL_JOYOEMCAL7'
,'REGSTR_VAL_JOYOEMCAL8'
,'REGSTR_VAL_JOYOEMCAL9'
,'REGSTR_VAL_JOYOEMCAL10'
,'REGSTR_VAL_JOYOEMCAL11'
,'REGSTR_VAL_JOYOEMCAL12'
);
var __RegisteredConstsList1 : TList;
procedure __RegisterConsts1;
begin
__RegisteredConstsList1 := TList.Create;
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[0] ,REGSTR_VALUE_SCRPASSWORD));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[1] ,REGSTR_VALUE_LOWPOWERTIMEOUT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[2] ,REGSTR_VALUE_POWEROFFTIMEOUT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[3] ,REGSTR_VALUE_LOWPOWERACTIVE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[4] ,REGSTR_VALUE_POWEROFFACTIVE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[5] ,REGSTR_PATH_WINDOWSAPPLETS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[6] ,REGSTR_PATH_SYSTRAY));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[7] ,REGSTR_VAL_SYSTRAYSVCS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[8] ,REGSTR_VAL_SYSTRAYBATFLAGS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[9] ,REGSTR_VAL_SYSTRAYPCCARDFLAGS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[10] ,REGSTR_PATH_NETWORK_USERSETTINGS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[11] ,REGSTR_KEY_NETWORK_PERSISTENT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[12] ,REGSTR_KEY_NETWORK_RECENT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[13] ,REGSTR_VAL_REMOTE_PATH));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[14] ,REGSTR_VAL_USER_NAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[15] ,REGSTR_VAL_PROVIDER_NAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[16] ,REGSTR_VAL_CONNECTION_TYPE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[17] ,REGSTR_VAL_UPGRADE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[18] ,REGSTR_KEY_LOGON));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[19] ,REGSTR_VAL_MUSTBEVALIDATED));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[20] ,REGSTR_VAL_RUNLOGINSCRIPT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[21] ,REGSTR_KEY_NETWORKPROVIDER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[22] ,REGSTR_PATH_NW32NETPROVIDER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[23] ,REGSTR_PATH_MS32NETPROVIDER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[24] ,REGSTR_VAL_AUTHENT_AGENT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[25] ,REGSTR_VAL_PREFREDIR));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[26] ,REGSTR_VAL_AUTOSTART));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[27] ,REGSTR_VAL_AUTOLOGON));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[28] ,REGSTR_VAL_NETCARD));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[29] ,REGSTR_VAL_DYNAMIC));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[30] ,REGSTR_VAL_STATICDRIVE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[31] ,REGSTR_VAL_LOADHI));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[32] ,REGSTR_VAL_LOADRMDRIVERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[33] ,REGSTR_VAL_SETUPN));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[34] ,REGSTR_VAL_SETUPNPATH));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[35] ,REGSTR_VAL_WRKGRP_FORCEMAPPING));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[36] ,REGSTR_VAL_WRKGRP_REQUIRED));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[37] ,REGSTR_PATH_CURRENT_CONTROL_SET));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[38] ,REGSTR_VAL_CURRENT_USER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[39] ,REGSTR_PATH_PWDPROVIDER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[40] ,REGSTR_VAL_PWDPROVIDER_PATH));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[41] ,REGSTR_VAL_PWDPROVIDER_DESC));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[42] ,REGSTR_VAL_PWDPROVIDER_CHANGEPWD));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[43] ,REGSTR_VAL_PWDPROVIDER_CHANGEPWDHWND));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[44] ,REGSTR_VAL_PWDPROVIDER_GETPWDSTATUS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[45] ,REGSTR_VAL_PWDPROVIDER_ISNP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[46] ,REGSTR_VAL_PWDPROVIDER_CHANGEORDER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[47] ,REGSTR_PATH_POLICIES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[48] ,REGSTR_PATH_UPDATE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[49] ,REGSTR_VALUE_ENABLE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[50] ,REGSTR_VALUE_VERBOSE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[51] ,REGSTR_VALUE_NETPATH));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[52] ,REGSTR_VALUE_DEFAULTLOC));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[53] ,REGSTR_KEY_NETWORK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[54] ,REGSTR_KEY_PRINTERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[55] ,REGSTR_KEY_WINOLDAPP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[56] ,REGSTR_VAL_NOFILESHARING));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[57] ,REGSTR_VAL_NOPRINTSHARING));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[58] ,REGSTR_VAL_NOFILESHARINGCTRL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[59] ,REGSTR_VAL_NOPRINTSHARINGCTRL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[60] ,REGSTR_VAL_HIDESHAREPWDS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[61] ,REGSTR_VAL_DISABLEPWDCACHING));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[62] ,REGSTR_VAL_ALPHANUMPWDS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[63] ,REGSTR_VAL_NETSETUP_DISABLE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[64] ,REGSTR_VAL_NETSETUP_NOCONFIGPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[65] ,REGSTR_VAL_NETSETUP_NOIDPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[66] ,REGSTR_VAL_NETSETUP_NOSECURITYPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[67] ,REGSTR_VAL_SYSTEMCPL_NOVIRTMEMPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[68] ,REGSTR_VAL_SYSTEMCPL_NODEVMGRPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[69] ,REGSTR_VAL_SYSTEMCPL_NOCONFIGPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[70] ,REGSTR_VAL_SYSTEMCPL_NOFILESYSPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[71] ,REGSTR_VAL_DISPCPL_NODISPCPL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[72] ,REGSTR_VAL_DISPCPL_NOBACKGROUNDPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[73] ,REGSTR_VAL_DISPCPL_NOSCRSAVPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[74] ,REGSTR_VAL_DISPCPL_NOAPPEARANCEPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[75] ,REGSTR_VAL_DISPCPL_NOSETTINGSPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[76] ,REGSTR_VAL_SECCPL_NOSECCPL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[77] ,REGSTR_VAL_SECCPL_NOPWDPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[78] ,REGSTR_VAL_SECCPL_NOADMINPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[79] ,REGSTR_VAL_SECCPL_NOPROFILEPAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[80] ,REGSTR_VAL_PRINTERS_HIDETABS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[81] ,REGSTR_VAL_PRINTERS_NODELETE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[82] ,REGSTR_VAL_PRINTERS_NOADD));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[83] ,REGSTR_VAL_WINOLDAPP_DISABLED));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[84] ,REGSTR_VAL_WINOLDAPP_NOREALMODE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[85] ,REGSTR_VAL_NOENTIRENETWORK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[86] ,REGSTR_VAL_NOWORKGROUPCONTENTS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[87] ,REGSTR_VAL_MINPWDLEN));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[88] ,REGSTR_VAL_PWDEXPIRATION));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[89] ,REGSTR_VAL_WIN31PROVIDER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[90] ,REGSTR_VAL_DISABLEREGTOOLS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[91] ,REGSTR_PATH_WINLOGON));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[92] ,REGSTR_VAL_LEGALNOTICECAPTION));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[93] ,REGSTR_VAL_LEGALNOTICETEXT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[94] ,REGSTR_VAL_RESTRICTRUN));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[95] ,REGSTR_KEY_POL_USERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[96] ,REGSTR_KEY_POL_COMPUTERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[97] ,REGSTR_KEY_POL_USERGROUPS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[98] ,REGSTR_KEY_POL_DEFAULT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[99] ,REGSTR_KEY_POL_USERGROUPDATA));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[100] ,REGSTR_PATH_TIMEZONE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[101] ,REGSTR_VAL_TZBIAS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[102] ,REGSTR_VAL_TZDLTBIAS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[103] ,REGSTR_VAL_TZSTDBIAS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[104] ,REGSTR_VAL_TZACTBIAS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[105] ,REGSTR_VAL_TZDLTFLAG));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[106] ,REGSTR_VAL_TZSTDSTART));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[107] ,REGSTR_VAL_TZDLTSTART));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[108] ,REGSTR_VAL_TZDLTNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[109] ,REGSTR_VAL_TZSTDNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[110] ,REGSTR_VAL_TZNOCHANGESTART));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[111] ,REGSTR_VAL_TZNOCHANGEEND));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[112] ,REGSTR_VAL_TZNOAUTOTIME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[113] ,REGSTR_PATH_FLOATINGPOINTPROCESSOR));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[114] ,REGSTR_PATH_FLOATINGPOINTPROCESSOR0));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[115] ,REGSTR_PATH_COMPUTRNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[116] ,REGSTR_VAL_COMPUTRNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[117] ,REGSTR_PATH_SHUTDOWN));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[118] ,REGSTR_VAL_FORCEREBOOT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[119] ,REGSTR_VAL_SETUPPROGRAMRAN));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[120] ,REGSTR_VAL_DOES_POLLING));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[121] ,REGSTR_PATH_KNOWNDLLS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[122] ,REGSTR_PATH_KNOWN16DLLS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[123] ,REGSTR_PATH_CHECKVERDLLS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[124] ,REGSTR_PATH_WARNVERDLLS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[125] ,REGSTR_PATH_HACKINIFILE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[126] ,REGSTR_PATH_CHECKBADAPPS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[127] ,REGSTR_PATH_APPPATCH));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[128] ,REGSTR_PATH_KNOWNVXDS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[129] ,REGSTR_VAL_UNINSTALLER_DISPLAYNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[130] ,REGSTR_VAL_UNINSTALLER_COMMANDLINE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[131] ,REGSTR_PATH_DESKTOP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[132] ,REGSTR_PATH_MOUSE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[133] ,REGSTR_PATH_KEYBOARD));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[134] ,REGSTR_PATH_COLORS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[135] ,REGSTR_PATH_SOUND));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[136] ,REGSTR_PATH_METRICS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[137] ,REGSTR_PATH_ICONS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[138] ,REGSTR_PATH_CURSORS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[139] ,REGSTR_PATH_CHECKDISK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[140] ,REGSTR_PATH_CHECKDISKSET));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[141] ,REGSTR_PATH_CHECKDISKUDRVS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[142] ,REGSTR_PATH_FAULT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[143] ,REGSTR_VAL_FAULT_LOGFILE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[144] ,REGSTR_PATH_AEDEBUG));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[145] ,REGSTR_VAL_AEDEBUG_DEBUGGER));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[146] ,REGSTR_VAL_AEDEBUG_AUTO));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[147] ,REGSTR_PATH_GRPCONV));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[148] ,REGSTR_VAL_REGITEMDELETEMESSAGE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[149] ,REGSTR_PATH_LASTCHECK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[150] ,REGSTR_PATH_LASTOPTIMIZE));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[151] ,REGSTR_PATH_LASTBACKUP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[152] ,REGSTR_PATH_CHKLASTCHECK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[153] ,REGSTR_PATH_CHKLASTSURFAN));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[154] ,DTRESULTOK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[155] ,DTRESULTFIX));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[156] ,DTRESULTPROB));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[157] ,DTRESULTPART));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[158] ,REGSTR_KEY_SHARES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[159] ,REGSTR_VAL_SHARES_FLAGS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[160] ,REGSTR_VAL_SHARES_PATH));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[161] ,REGSTR_VAL_SHARES_REMARK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[162] ,REGSTR_VAL_SHARES_RW_PASS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[163] ,REGSTR_VAL_SHARES_RO_PASS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[164] ,REGSTR_PATH_PRINT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[165] ,REGSTR_PATH_PRINTERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[166] ,REGSTR_PATH_PROVIDERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[167] ,REGSTR_PATH_MONITORS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[168] ,REGSTR_PATH_ENVIRONMENTS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[169] ,REGSTR_VAL_START_ON_BOOT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[170] ,REGSTR_VAL_PRINTERS_MASK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[171] ,REGSTR_VAL_DOS_SPOOL_MASK));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[172] ,REGSTR_KEY_CURRENT_ENV));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[173] ,REGSTR_KEY_DRIVERS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[174] ,REGSTR_KEY_PRINT_PROC));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[175] ,REGSTR_PATH_EVENTLABELS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[176] ,REGSTR_PATH_SCHEMES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[177] ,REGSTR_PATH_APPS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[178] ,REGSTR_PATH_APPS_DEFAULT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[179] ,REGSTR_PATH_NAMES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[180] ,REGSTR_PATH_MULTIMEDIA));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[181] ,REGSTR_PATH_MULTIMEDIA_AUDIO));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[182] ,REGSTR_PATH_MEDIARESOURCES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[183] ,REGSTR_PATH_MEDIAPROPERTIES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[184] ,REGSTR_PATH_PRIVATEPROPERTIES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[185] ,REGSTR_PATH_PUBLICPROPERTIES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[186] ,REGSTR_PATH_JOYOEM));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[187] ,REGSTR_PATH_JOYCONFIG));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[188] ,REGSTR_KEY_JOYCURR));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[189] ,REGSTR_KEY_JOYSETTINGS));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[190] ,REGSTR_VAL_JOYUSERVALUES));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[191] ,REGSTR_VAL_JOYCALLOUT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[192] ,REGSTR_VAL_JOYNCONFIG));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[193] ,REGSTR_VAL_JOYNOEMNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[194] ,REGSTR_VAL_JOYNOEMCALLOUT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[195] ,REGSTR_VAL_JOYOEMCALLOUT));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[196] ,REGSTR_VAL_JOYOEMNAME));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[197] ,REGSTR_VAL_JOYOEMDATA));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[198] ,REGSTR_VAL_JOYOEMXYLABEL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[199] ,REGSTR_VAL_JOYOEMZLABEL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[200] ,REGSTR_VAL_JOYOEMRLABEL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[201] ,REGSTR_VAL_JOYOEMPOVLABEL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[202] ,REGSTR_VAL_JOYOEMULABEL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[203] ,REGSTR_VAL_JOYOEMVLABEL));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[204] ,REGSTR_VAL_JOYOEMTESTMOVEDESC));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[205] ,REGSTR_VAL_JOYOEMTESTBUTTONDESC));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[206] ,REGSTR_VAL_JOYOEMTESTMOVECAP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[207] ,REGSTR_VAL_JOYOEMTESTBUTTONCAP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[208] ,REGSTR_VAL_JOYOEMTESTWINCAP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[209] ,REGSTR_VAL_JOYOEMCALCAP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[210] ,REGSTR_VAL_JOYOEMCALWINCAP));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[211] ,REGSTR_VAL_JOYOEMCAL1));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[212] ,REGSTR_VAL_JOYOEMCAL2));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[213] ,REGSTR_VAL_JOYOEMCAL3));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[214] ,REGSTR_VAL_JOYOEMCAL4));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[215] ,REGSTR_VAL_JOYOEMCAL5));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[216] ,REGSTR_VAL_JOYOEMCAL6));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[217] ,REGSTR_VAL_JOYOEMCAL7));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[218] ,REGSTR_VAL_JOYOEMCAL8));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[219] ,REGSTR_VAL_JOYOEMCAL9));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[220] ,REGSTR_VAL_JOYOEMCAL10));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[221] ,REGSTR_VAL_JOYOEMCAL11));
__RegisteredConstsList1.Add(RegisterConst(__ConstNames1[222] ,REGSTR_VAL_JOYOEMCAL12));
end;

procedure __UnregisterConsts1;
var i : integer;
begin
__RegisteredConstsList1.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..2] of string = (
'_DSKTLSYSTEMTIME'
,'DSKTLSYSTEMTIME'
,'TDSKTLSystemTime'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
__RegisteredMethods.Add(RegisterRWProc(MethodNames[0],Addr(__DSKTLSYSTEMTIME_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[1],Addr(_DSKTLSYSTEMTIME_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[2],Addr(_TDSKTLSystemTime_)));
end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterConsts1;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterConsts1;
__UnregisterProcs;
end.
