Bin\   OPP_Guide_API_D2006,
  OPP_Guide_API_Context_D2006,
  OPP_Guide_API_Context_Step_D2006,
  OPP_Guide_API_Context_Step_Process_D2006,
  OPP_Guide_API_Context_Step_Result_D2006,
  OPP_Guide_API_Context_Step_SendMessage_Help_D2006,
  OPP_Guide_API_Identifiable_D2006,
  OPP_Guide_API_Scripter_D2006,
  OPP_Help_System_Messaging_Pipe_D2006,
  OPPGuideAPIContext_D2006,
  Proxy_OPPHelpPredicate_D2006,
  OPP_Help_API_D2006; -I;C:\delphi_libs\my_libs\dc_412\utils\unitimporter\delphi\..\..\..\UNITS\;D:\GulfStream\Sources\Common\Help\OPP.Guide.API\exportable\;D:\GulfStream\Sources\Common\Help\OPP.Help\ -U;C:\delphi_libs\my_libs\dc_412\utils\unitimporter\delphi\..\..\..\UNITS\;D:\GulfStream\Sources\Common\Help\OPP.Guide.API\exportable\;D:\GulfStream\Sources\Common\Help\OPP.Help\ -LUdesignide;dclwbm;dcldss;dclado;dclcds dctestunit.pas
